export enum NotificationType {
  ORDER_VALIDATED = 'ORDER_VALIDATED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_EXPIRED = 'ORDER_EXPIRED',
  VENDOR_SUMMARY = 'VENDOR_SUMMARY',
  TOPUP_SUCCESS = 'TOPUP_SUCCESS',
  TOPUP_FAILED = 'TOPUP_FAILED',
  WITHDRAWAL_SUCCESS = 'WITHDRAWAL_SUCCESS',
  WITHDRAWAL_FAILED = 'WITHDRAWAL_FAILED',
}
